name: 'cheyenne'

on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
    - name: 'Set up Python'
      uses: 'actions/setup-python@v2'
      with:
        python-version: '3.8'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install \
          --no-python-version-warning \
          --disable-pip-version-check \
          --progress-bar off \
          --quiet \
          --no-input \
            pylint \
            boto3 \
            python-json-logger
    - name: 'Lint'
      run: |
        find ./functions/ -type f -iname '*.py' -print0 | xargs -0 python -m pylint --rcfile ./.pylintrc
    - name: 'Syntax check shell scripts'
      run: |
        find . -type f -iname "*.sh" -print0 | xargs -0 bash -n
    - name: 'Run build script'
      run: |
        bash build.sh
    - name: 'Upload deploy artifact'
      uses: 'actions/upload-artifact@v2'
      with:
        name: 'cheyenne_deploy'
        path: 'dist/*'
        retention-days: 5
